on:
  push:
    branches:
      - main
name: 🚀 Deploy site on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.pdinformatica.com.br
          username: luiz@pdinformatica.com.br
          password: XUd@JL2PZ55
          server-dir: apps_pd/deploy/
